# Generated by Django 4.2 on 2023-04-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Care_Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField()),
                ('food', models.CharField(max_length=100)),
                ('light', models.CharField(choices=[('S', 'Full Sun'), ('PS', 'Partial Sun'), ('FS', 'Full Shade')], default='S')),
                ('water', models.CharField()),
                ('companions', models.CharField()),
                ('notes', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('variety', models.CharField(max_length=100)),
                ('seeds_sown', models.IntegerField()),
                ('germination', models.DateField()),
                ('care_guide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.care_guide')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField()),
                ('date', models.DateField()),
                ('journal', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
