# Generated by Django 4.2 on 2023-04-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_garden_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='care_guide',
        ),
        migrations.AddField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.garden'),
        ),
    ]
