# Generated by Django 4.2 on 2023-04-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_plant_care_guide_plant_garden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='plant',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.garden'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='germination',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='seeds_sown',
            field=models.IntegerField(blank=True),
        ),
    ]
