# Generated by Django 4.2 on 2023-04-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_plant_options_alter_plant_garden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='germination',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='seeds_sown',
            field=models.IntegerField(null=True),
        ),
    ]
